openapi: 3.1.0
x-stoplight:
  id: fft2t0cl79d5e
info:
  title: spec
  version: '1.0'
  contact:
    name: kirill kikimov
    email: gluck1986@gmail.com
  license:
    name: MIT
servers:
  - url: 'http://localhost:8080'
    description: local
paths:
  /catalog:
    post:
      summary: get products and filters
      operationId: post-catalog
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        guid:
                          type: string
                        name:
                          type: string
                        cost:
                          type: number
                        descr:
                          type: string
                        delivery:
                          type: integer
                        attr:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              value:
                                type: string
                            required:
                              - id
                              - name
                              - value
                      required:
                        - guid
                        - name
                        - cost
                        - descr
                        - delivery
                        - attr
                  filters:
                    type: object
                    required:
                      - costFrom
                      - costTo
                      - delivery
                      - attr
                    properties:
                      costFrom:
                        type: number
                      costTo:
                        type: number
                      delivery:
                        type: integer
                      attr:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            values:
                              type: array
                              items:
                                type: string
                          required:
                            - id
                            - name
                            - values
                  summary:
                    type: object
                    required:
                      - page
                      - totalPages
                      - totalItems
                      - pageSize
                    properties:
                      page:
                        type: integer
                      totalPages:
                        type: integer
                      totalItems:
                        type: integer
                      pageSize:
                        type: integer
                required:
                  - products
                  - filters
                  - summary
              examples:
                example-1:
                  value:
                    products:
                      - guid: string
                        name: string
                        cost: string
                        descr: string
                        attr:
                          - id: 0
                            name: string
                            value: string
                    filters:
                      costFrom: 0
                      costTo: 0
                      attr:
                        - id: 0
                          name: string
                          values:
                            - value: string
                              count: 0
                    summary:
                      page: 0
                      totalPages: 0
                      totalItems: 0
                      pageSize: 0
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  type: object
                  properties:
                    name:
                      type: string
                    costFrom:
                      type: number
                    costTo:
                      type: number
                    delivery:
                      type: integer
                    attr:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          values:
                            type: array
                            items:
                              type: string
                        required:
                          - id
                          - values
                group:
                  type: integer
                page:
                  type: integer
                pageSize:
                  type: integer
              required:
                - filters
                - group
            examples:
              example-1:
                value:
                  filters:
                    name: string
                    costFrom: 0
                    costTo: 100.99
                    delivery: 0
                    attr:
                      - id: 0
                        values:
                          - string
                    group: string
                  group: string
                  page: 0
                  pageSize: 10
        description: ''
      description: get products with filters by filter
  /groups:
    get:
      summary: get groups
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
      operationId: get-groups
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
