openapi: 3.1.0
x-stoplight:
  id: fft2t0cl79d5e
info:
  title: spec
  version: '1.0'
  contact:
    name: kirill kikimov
    email: gluck1986@gmail.com
  license:
    name: MIT
servers:
  - url: 'http://localhost:8080'
    description: local
  - url: 'http://2.58.68.23'
    description: prod
paths:
  /catalog:
    post:
      summary: get products and filters
      operationId: post-catalog
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        guid:
                          type: string
                        name:
                          type: string
                        cost:
                          type: number
                        descr:
                          type: string
                        delivery:
                          type: integer
                        attr:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              value:
                                type: string
                            required:
                              - id
                              - name
                              - value
                      required:
                        - guid
                        - name
                        - cost
                        - descr
                        - delivery
                        - attr
                  filters:
                    type: object
                    required:
                      - costFrom
                      - costTo
                      - delivery
                      - attr
                    properties:
                      costFrom:
                        type: number
                      costTo:
                        type: number
                      delivery:
                        type: array
                        items:
                          type: integer
                      attr:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            values:
                              type: array
                              items:
                                type: string
                          required:
                            - id
                            - name
                            - values
                  summary:
                    type: object
                    required:
                      - page
                      - totalPages
                      - totalItems
                      - pageSize
                    properties:
                      page:
                        type: integer
                      totalPages:
                        type: integer
                      totalItems:
                        type: integer
                      pageSize:
                        type: integer
                required:
                  - products
                  - filters
                  - summary
              examples:
                example-1:
                  value:
                    products:
                      - guid: string
                        name: string
                        cost: 0
                        descr: string
                        delivery: 0
                        attr:
                          - id: 0
                            name: string
                            value: string
                    filters:
                      costFrom: 0
                      costTo: 0
                      delivery:
                        - 0
                      attr:
                        - id: 0
                          name: string
                          values:
                            - string
                    summary:
                      page: 0
                      totalPages: 0
                      totalItems: 0
                      pageSize: 0
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  type: object
                  properties:
                    name:
                      type: string
                    costFrom:
                      type: number
                    costTo:
                      type: number
                    delivery:
                      type: integer
                    attr:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            minimum: 1
                          values:
                            type: array
                            minItems: 1
                            items:
                              type: string
                        required:
                          - id
                          - values
                group:
                  type: integer
                  minimum: 1
                page:
                  type: integer
                  minimum: 1
                pageSize:
                  type: integer
              required:
                - filters
                - group
            examples:
              example-1:
                value:
                  filters:
                    name: string
                    costFrom: 0
                    costTo: 0
                    delivery: 1
                    attr:
                      - id: 1
                        values:
                          - string
                  group: 1
                  page: 1
                  pageSize: 10
        description: ''
      description: get products with filters by filter
  /groups:
    get:
      summary: get groups
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
      operationId: get-groups
components:
  schemas: {}
